server:
    port: 9071
spring:
    application:
      name: ace-user
    datasource:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.238:3306/wh_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: lym
      password: bwyf1111
    jpa:
      show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
